version: '3.8'

services:
  websocket:
    image: node:18-alpine
    container_name: websocket-server
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    command: sh -c "npm install && node server.js"
    restart: unless-stopped
