services:
  websocket:
    image: node:18-alpine
    container_name: server
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    command: sh -c "npm install && node server.js"
    restart: unless-stopped
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
